{"uuid": "11bb289a-5bc0-45cb-adf8-321df4b5535b", "children": ["4de1a402-6af8-4e6e-bfb4-e6a156dc9c65", "5b55ecc0-5a09-4e9f-a862-9a06e8db69c7", "1e55bc6b-3376-41c9-98ba-64a627520995", "c7ab5afa-379d-4edc-8b14-dfd2d2dd4a70", "a30dd4bc-3150-4599-828a-0160d35b4a16", "469de928-c019-49b6-a79a-d3338e6ce042", "d74322f0-7b92-4899-b2ba-cbcad5ad137d", "cf359b48-6f50-4af9-af11-120b7288c13b", "7c85a27b-59c2-4f5e-bb2a-4783d6f6ab62", "2cb6bdf9-934d-4eca-8e80-047a725217e0", "7230888b-e880-4b99-9128-8ed8291f1e5a"], "befores": [{"name": "funcInfo", "status": "passed", "start": 1684067882486, "stop": 1684067882487}], "afters": [{"name": "funcInfo::0", "status": "broken", "statusDetails": {"message": "AttributeError: module 'datetime' has no attribute 'today'\n", "trace": "  File \"C:\\Users\\14917\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\14917\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\PycharmProjects\\电商接口自动化项目\\case\\conftest.py\", line 45, in funcInfo\n    log_list = [os.path.join(log_dir, i) for i in os.listdir(log_dir) if i == datetime.today().strftime(\"%Y-%m-%d\")]\n  File \"D:\\PycharmProjects\\电商接口自动化项目\\case\\conftest.py\", line 45, in <listcomp>\n    log_list = [os.path.join(log_dir, i) for i in os.listdir(log_dir) if i == datetime.today().strftime(\"%Y-%m-%d\")]\n"}, "start": 1684067891447, "stop": 1684067891452}], "start": 1684067882486, "stop": 1684067891452}